### Healthcheck
GET http://localhost:4000/v1/healthcheck

### Create Movie
POST http://localhost:4000/v1/movies
Context-Type: application/json

{
    "title": "Black Panther",
    "year": 2018,
    "runtime": "134 mins",
    "genres": [
        "action",
        "adventure",
        "sci-fi"
    ]
}

### Get Movie by ID
GET http://localhost:4000/v1/movies/3

### Update Movie by ID
PUT http://localhost:4000/v1/movies/2

{
    "title": "Black Panther",
    "year": 2018,
    "runtime": "134 mins",
    "genres": [
        "action",
        "adventure",
        "sci-fi"
    ]
}

### Delete by ID
DELETE http://localhost:4000/v1/movies/6